package cfrida

var(
	g_free = libfrida.NewProc("g_free")
	g_object_ref = libfrida.NewProc("g_object_ref")
	g_object_unref = libfrida.NewProc("g_object_unref")
	g_signal_connect_data = libfrida.NewProc("g_signal_connect_data")
	g_signal_handler_disconnect = libfrida.NewProc("g_signal_handler_disconnect")
	g_strlen = libfrida.NewProc("g_strlen")
	g_ref_string_length = libfrida.NewProc("g_ref_string_length")
	g_error_get_message = libfrida.NewProc("g_error_get_message")
	g_error_get_code = libfrida.NewProc("g_error_get_code")
	g_error_free = libfrida.NewProc("g_error_free")
	g_io_stream_close = libfrida.NewProc("g_io_stream_close")
	g_input_stream_read_bytes = libfrida.NewProc("g_input_stream_read_bytes")
	g_output_stream_write_bytes = libfrida.NewProc("g_output_stream_write_bytes")
	g_output_stream_write_all = libfrida.NewProc("g_output_stream_write_all")
	g_input_stream_read_all = libfrida.NewProc("g_input_stream_read_all")
	g_io_stream_is_closed = libfrida.NewProc("g_io_stream_is_closed")
	g_io_stream_get_input_stream = libfrida.NewProc("g_io_stream_get_input_stream")
	g_io_stream_get_output_stream = libfrida.NewProc("g_io_stream_get_output_stream")
	g_io_stream_has_pending = libfrida.NewProc("g_io_stream_has_pending")
	g_io_stream_set_pending = libfrida.NewProc("g_io_stream_set_pending")
	g_io_stream_clear_pending = libfrida.NewProc("g_io_stream_clear_pending")
	g_bytes_get_data = libfrida.NewProc("g_bytes_get_data")
	g_bytes_get_size = libfrida.NewProc("g_bytes_get_size")
	g_bytes_ref = libfrida.NewProc("g_bytes_ref")
	g_bytes_unref = libfrida.NewProc("g_bytes_unref")
	g_bytes_new = libfrida.NewProc("g_bytes_new")
)
